"use server";

import {
  revalidatePath,
} from "next/cache";

import {
  compare,
  hash,
} from "bcryptjs";

import {
  z,
} from "zod";

import {
  requireAdmin,
} from "@/lib/auth/session";

import {
  getSupabaseAdmin,
} from "@/lib/supabase/admin";

/* =========================================================
   VALIDATION
========================================================= */

const currentPasswordSchema =
  z.string()
    .min(
      1,
      "Enter your current password.",
    )
    .max(
      256,
      "Invalid password.",
    );

const updateAccountSchema =
  z.object({
    fullName:
      z.string()
        .trim()
        .max(
          100,
          "Full name must be 100 characters or fewer.",
        ),

    email:
      z.string()
        .trim()
        .toLowerCase()
        .email(
          "Enter a valid email address.",
        )
        .max(
          254,
          "Email address is too long.",
        ),

    currentPassword:
      currentPasswordSchema,
  });

const changePasswordSchema =
  z.object({
    currentPassword:
      currentPasswordSchema,

    newPassword:
      z.string()
        .min(
          12,
          "New password must contain at least 12 characters.",
        )
        .max(
          72,
          "New password must contain 72 characters or fewer.",
        ),

    confirmPassword:
      z.string(),
  })
    .refine(
      (
        values,
      ) =>
        values.newPassword ===
        values.confirmPassword,
      {
        path: [
          "confirmPassword",
        ],

        message:
          "The new passwords do not match.",
      },
    );

const savePolicySchema =
  z.object({
    key:
      z.string()
        .trim()
        .min(
          1,
          "Policy key is required.",
        ),

    value:
      z.string(),
  });

const revokeSessionsSchema =
  z.object({
    currentPassword:
      currentPasswordSchema,
  });

/* =========================================================
   RESULT TYPES
========================================================= */

export type AdminAccountActionResult =
  | {
      success: true;

      message: string;

      requiresReauth:
        boolean;

      account?: {
        id: string;

        full_name:
          string | null;

        email:
          string;

        role:
          string;

        status:
          string;

        updated_at:
          string | null;
      };
    }
  | {
      success: false;

      message: string;

      field?:
        | "fullName"
        | "email"
        | "currentPassword"
        | "newPassword"
        | "confirmPassword";
    };

export type PolicyActionResult =
  | {
      success: true;

      message: string;

      setting: {
        id: number;

        key: string;

        value:
          string | null;

        updated_by:
          string | null;

        updated_at:
          string | null;
      };
    }
  | {
      success: false;

      message: string;
    };

export type SessionActionResult =
  | {
      success: true;

      message: string;

      requiresReauth: true;
    }
  | {
      success: false;

      message: string;
    };

/* =========================================================
   INTERNAL TYPES
========================================================= */

type AdminCredentialRow = {
  id: string;

  email: string;

  password: string;

  full_name:
    string | null;

  role: string;

  status: string;

  updated_at:
    string | null;
};

type RawPolicySetting = {
  id:
    number | string;

  key: string;

  value:
    string | null;

  type: string;

  grp:
    string | null;

  description:
    string | null;

  updated_by:
    string | null;

  updated_at:
    string | null;
};

/* =========================================================
   PASSWORD HELPERS
========================================================= */

/*
 * Passwords originally generated by PHP password_hash()
 * may begin with $2y$.
 *
 * bcryptjs understands the equivalent $2b$ prefix.
 */
function normalizeBcryptHash(
  value: string,
): string {
  if (
    value.startsWith(
      "$2y$",
    )
  ) {
    return `$2b$${value.slice(
      4,
    )}`;
  }

  if (
    value.startsWith(
      "$2a$",
    )
  ) {
    return `$2b$${value.slice(
      4,
    )}`;
  }

  return value;
}

async function getAuthenticatedAdminWithPassword(): Promise<
  | {
      success: true;

      admin:
        AdminCredentialRow;
    }
  | {
      success: false;

      message: string;
    }
> {
  const currentAdmin =
    await requireAdmin();

  const supabase =
    getSupabaseAdmin();

  const {
    data,
    error,
  } =
    await supabase
      .from(
        "admins",
      )
      .select(`
        id,
        email,
        password,
        full_name,
        role,
        status,
        updated_at
      `)
      .eq(
        "id",
        currentAdmin.id,
      )
      .maybeSingle();

  if (
    error
  ) {
    console.error(
      "[ADMIN SETTINGS] Failed to load authenticated admin:",
      error,
    );

    return {
      success:
        false,

      message:
        "Unable to verify your administrator account.",
    };
  }

  if (
    !data
  ) {
    return {
      success:
        false,

      message:
        "Administrator account was not found.",
    };
  }

  if (
    data.status !==
    "active"
  ) {
    return {
      success:
        false,

      message:
        "Your administrator account is not active.",
    };
  }

  return {
    success:
      true,

    admin:
      data as AdminCredentialRow,
  };
}

async function verifyCurrentPassword(
  admin:
    AdminCredentialRow,
  currentPassword:
    string,
): Promise<boolean> {
  if (
    !admin.password
  ) {
    return false;
  }

  try {
    return await compare(
      currentPassword,
      normalizeBcryptHash(
        admin.password,
      ),
    );
  } catch (
    error
  ) {
    console.error(
      "[ADMIN SETTINGS] Password verification failed:",
      error,
    );

    return false;
  }
}

/* =========================================================
   POLICY HELPERS
========================================================= */

function isPolicySetting(
  setting:
    RawPolicySetting,
): boolean {
  const key =
    setting.key
      .trim()
      .toLowerCase();

  const group =
    (
      setting.grp ??
      ""
    )
      .trim()
      .toLowerCase();

  const policyTerms = [
    "policy",
    "policies",
    "privacy",
    "terms",
    "legal",
    "agreement",
    "consent",
    "guideline",
    "community_guideline",
    "community-guideline",
  ];

  return policyTerms.some(
    (
      term,
    ) =>
      key.includes(
        term,
      ) ||
      group.includes(
        term,
      ),
  );
}

/* =========================================================
   AUDIT LOGGING
========================================================= */

async function writeAdminAuditLog({
  adminId,
  actionType,
  description,
  targetTable,
  targetId,
}: {
  adminId: string;

  actionType:
    string;

  description:
    string;

  targetTable:
    string | null;

  targetId:
    string | null;
}) {
  const supabase =
    getSupabaseAdmin();

  const {
    error,
  } =
    await supabase
      .from(
        "logs",
      )
      .insert({
        user_id:
          adminId,

        actor_type:
          "admin",

        action_type:
          actionType,

        description,

        target_table:
          targetTable,

        target_id:
          targetId,

        ip_address:
          null,

        user_agent:
          null,

        created_at:
          new Date()
            .toISOString(),
      });

  if (
    error
  ) {
    /*
     * A logging problem should be visible
     * to the server operator, but it should
     * not undo an otherwise valid account
     * or policy update.
     */
    console.error(
      "[ADMIN SETTINGS] Audit log insert failed:",
      error,
    );
  }
}

/* =========================================================
   SESSION REVOCATION
========================================================= */

async function revokeAdminSessions(
  adminId:
    string,
): Promise<boolean> {
  const supabase =
    getSupabaseAdmin();

  const {
    error,
  } =
    await supabase
      .from(
        "admin_sessions",
      )
      .delete()
      .eq(
        "admin_id",
        adminId,
      );

  if (
    error
  ) {
    console.error(
      "[ADMIN SETTINGS] Failed to revoke admin sessions:",
      error,
    );

    return false;
  }

  return true;
}

function refreshAdminPages() {
  revalidatePath(
    "/admin/settings",
  );

  revalidatePath(
    "/admin",
    "layout",
  );
}

/* =========================================================
   UPDATE ADMIN PROFILE / EMAIL
========================================================= */

export async function updateAdminAccountAction(
  input: {
    fullName:
      string;

    email:
      string;

    currentPassword:
      string;
  },
): Promise<AdminAccountActionResult> {
  const parsed =
    updateAccountSchema.safeParse(
      input,
    );

  if (
    !parsed.success
  ) {
    const issue =
      parsed.error
        .issues[0];

    const field =
      issue?.path[0];

    return {
      success:
        false,

      message:
        issue?.message ??
        "Check the account details and try again.",

      field:
        field ===
          "fullName" ||
        field ===
          "email" ||
        field ===
          "currentPassword"
          ? field
          : undefined,
    };
  }

  const authenticated =
    await getAuthenticatedAdminWithPassword();

  if (
    !authenticated.success
  ) {
    return authenticated;
  }

  const {
    admin,
  } =
    authenticated;

  const {
    fullName,
    email,
    currentPassword,
  } =
    parsed.data;

  const passwordValid =
    await verifyCurrentPassword(
      admin,
      currentPassword,
    );

  if (
    !passwordValid
  ) {
    return {
      success:
        false,

      message:
        "Your current password is incorrect.",

      field:
        "currentPassword",
    };
  }

  const normalizedFullName =
    fullName.length >
    0
      ? fullName
      : null;

  const normalizedEmail =
    email.toLowerCase();

  const currentEmail =
    admin.email
      .trim()
      .toLowerCase();

  const emailChanged =
    normalizedEmail !==
    currentEmail;

  const nameChanged =
    normalizedFullName !==
    (
      admin.full_name ??
      null
    );

  if (
    !emailChanged &&
    !nameChanged
  ) {
    return {
      success:
        true,

      message:
        "No account changes were necessary.",

      requiresReauth:
        false,

      account: {
        id:
          admin.id,

        full_name:
          admin.full_name,

        email:
          admin.email,

        role:
          admin.role,

        status:
          admin.status,

        updated_at:
          admin.updated_at,
      },
    };
  }

  const supabase =
    getSupabaseAdmin();

  /*
   * Email is unique in public.admins.
   *
   * Check for another administrator
   * before attempting the update so the
   * user receives a useful error.
   */
  if (
    emailChanged
  ) {
    const {
      data:
        emailOwner,

      error:
        emailLookupError,
    } =
      await supabase
        .from(
          "admins",
        )
        .select(
          "id",
        )
        .eq(
          "email",
          normalizedEmail,
        )
        .neq(
          "id",
          admin.id,
        )
        .maybeSingle();

    if (
      emailLookupError
    ) {
      console.error(
        "[ADMIN SETTINGS] Failed to check admin email:",
        emailLookupError,
      );

      return {
        success:
          false,

        message:
          "Unable to verify whether this email address is available.",

        field:
          "email",
      };
    }

    if (
      emailOwner
    ) {
      return {
        success:
          false,

        message:
          "That email address is already being used by another administrator.",

        field:
          "email",
      };
    }
  }

  /*
   * Changing the login email is a
   * credential-sensitive operation.
   *
   * Revoke existing sessions before
   * applying the email change. This
   * prevents old authenticated sessions
   * from remaining valid after the login
   * identity changes.
   */
  if (
    emailChanged
  ) {
    const revoked =
      await revokeAdminSessions(
        admin.id,
      );

    if (
      !revoked
    ) {
      return {
        success:
          false,

        message:
          "Unable to securely revoke existing sessions. The email address was not changed.",
      };
    }
  }

  const now =
    new Date()
      .toISOString();

  const {
    data:
      updatedAdmin,

    error:
      updateError,
  } =
    await supabase
      .from(
        "admins",
      )
      .update({
        full_name:
          normalizedFullName,

        email:
          normalizedEmail,

        updated_at:
          now,

        /*
         * An email change revoked every
         * session, including this one.
         */
        ...(emailChanged
          ? {
              is_online:
                false,

              last_seen:
                now,
            }
          : {}),
      })
      .eq(
        "id",
        admin.id,
      )
      .select(`
        id,
        email,
        full_name,
        role,
        status,
        updated_at
      `)
      .single();

  if (
    updateError ||
    !updatedAdmin
  ) {
    console.error(
      "[ADMIN SETTINGS] Failed to update admin account:",
      updateError,
    );

    return {
      success:
        false,

      message:
        emailChanged
          ? "Your sessions were revoked, but the account update failed. Sign in again and retry."
          : "Unable to update your administrator account.",
    };
  }

  const changedFields:
    string[] = [];

  if (
    nameChanged
  ) {
    changedFields.push(
      "full name",
    );
  }

  if (
    emailChanged
  ) {
    changedFields.push(
      "email address",
    );
  }

  await writeAdminAuditLog({
    adminId:
      admin.id,

    actionType:
      "admin_account_updated",

    description:
      `Administrator updated their ${changedFields.join(
        " and ",
      )}.`,

    targetTable:
      "admins",

    targetId:
      admin.id,
  });

  refreshAdminPages();

  return {
    success:
      true,

    message:
      emailChanged
        ? "Account updated successfully. Because your login email changed, sign in again using the new email address."
        : "Administrator account updated successfully.",

    requiresReauth:
      emailChanged,

    account: {
      id:
        updatedAdmin.id,

      full_name:
        updatedAdmin.full_name,

      email:
        updatedAdmin.email,

      role:
        updatedAdmin.role,

      status:
        updatedAdmin.status,

      updated_at:
        updatedAdmin.updated_at,
    },
  };
}

/* =========================================================
   CHANGE ADMIN PASSWORD
========================================================= */

export async function changeAdminPasswordAction(
  input: {
    currentPassword:
      string;

    newPassword:
      string;

    confirmPassword:
      string;
  },
): Promise<AdminAccountActionResult> {
  const parsed =
    changePasswordSchema.safeParse(
      input,
    );

  if (
    !parsed.success
  ) {
    const issue =
      parsed.error
        .issues[0];

    const field =
      issue?.path[0];

    return {
      success:
        false,

      message:
        issue?.message ??
        "Check the password fields and try again.",

      field:
        field ===
          "currentPassword" ||
        field ===
          "newPassword" ||
        field ===
          "confirmPassword"
          ? field
          : undefined,
    };
  }

  const authenticated =
    await getAuthenticatedAdminWithPassword();

  if (
    !authenticated.success
  ) {
    return authenticated;
  }

  const {
    admin,
  } =
    authenticated;

  const {
    currentPassword,
    newPassword,
  } =
    parsed.data;

  const passwordValid =
    await verifyCurrentPassword(
      admin,
      currentPassword,
    );

  if (
    !passwordValid
  ) {
    return {
      success:
        false,

      message:
        "Your current password is incorrect.",

      field:
        "currentPassword",
    };
  }

  /*
   * Do not allow the current password
   * to be reused as the new password.
   */
  const samePassword =
    await compare(
      newPassword,
      normalizeBcryptHash(
        admin.password,
      ),
    );

  if (
    samePassword
  ) {
    return {
      success:
        false,

      message:
        "Your new password must be different from your current password.",

      field:
        "newPassword",
    };
  }

  let passwordHash:
    string;

  try {
    /*
     * Cost factor 12 provides a stronger
     * password hash while remaining
     * compatible with bcrypt verification
     * used by the admin login system.
     */
    passwordHash =
      await hash(
        newPassword,
        12,
      );
  } catch (
    error
  ) {
    console.error(
      "[ADMIN SETTINGS] Failed to hash new password:",
      error,
    );

    return {
      success:
        false,

      message:
        "Unable to securely process the new password.",
    };
  }

  /*
   * Revoke all current sessions BEFORE
   * replacing the credential.
   *
   * The server action already has the
   * authenticated admin ID in memory and
   * can finish the password update after
   * revocation.
   */
  const revoked =
    await revokeAdminSessions(
      admin.id,
    );

  if (
    !revoked
  ) {
    return {
      success:
        false,

      message:
        "Unable to securely revoke existing sessions. Your password was not changed.",
    };
  }

  const supabase =
    getSupabaseAdmin();

  const now =
    new Date()
      .toISOString();

  const {
    error:
      passwordUpdateError,
  } =
    await supabase
      .from(
        "admins",
      )
      .update({
        password:
          passwordHash,

        updated_at:
          now,

        is_online:
          false,

        last_seen:
          now,
      })
      .eq(
        "id",
        admin.id,
      );

  if (
    passwordUpdateError
  ) {
    console.error(
      "[ADMIN SETTINGS] Failed to update admin password:",
      passwordUpdateError,
    );

    return {
      success:
        false,

      message:
        "Your sessions were revoked, but the password update failed. Sign in again and retry.",
    };
  }

  await writeAdminAuditLog({
    adminId:
      admin.id,

    actionType:
      "admin_password_changed",

    description:
      "Administrator changed their account password.",

    targetTable:
      "admins",

    targetId:
      admin.id,
  });

  refreshAdminPages();

  return {
    success:
      true,

    message:
      "Password changed successfully. All administrator sessions were signed out. Sign in again using your new password.",

    requiresReauth:
      true,
  };
}

/* =========================================================
   REVOKE ALL ADMIN SESSIONS
========================================================= */

export async function revokeAllAdminSessionsAction(
  input: {
    currentPassword:
      string;
  },
): Promise<SessionActionResult> {
  const parsed =
    revokeSessionsSchema.safeParse(
      input,
    );

  if (
    !parsed.success
  ) {
    return {
      success:
        false,

      message:
        parsed.error
          .issues[0]
          ?.message ??
        "Enter your current password.",
    };
  }

  const authenticated =
    await getAuthenticatedAdminWithPassword();

  if (
    !authenticated.success
  ) {
    return {
      success:
        false,

      message:
        authenticated.message,
    };
  }

  const {
    admin,
  } =
    authenticated;

  const passwordValid =
    await verifyCurrentPassword(
      admin,
      parsed.data
        .currentPassword,
    );

  if (
    !passwordValid
  ) {
    return {
      success:
        false,

      message:
        "Your current password is incorrect.",
    };
  }

  const revoked =
    await revokeAdminSessions(
      admin.id,
    );

  if (
    !revoked
  ) {
    return {
      success:
        false,

      message:
        "Unable to revoke administrator sessions.",
    };
  }

  const supabase =
    getSupabaseAdmin();

  const now =
    new Date()
      .toISOString();

  const {
    error:
      presenceError,
  } =
    await supabase
      .from(
        "admins",
      )
      .update({
        is_online:
          false,

        last_seen:
          now,

        updated_at:
          now,
      })
      .eq(
        "id",
        admin.id,
      );

  if (
    presenceError
  ) {
    console.error(
      "[ADMIN SETTINGS] Failed to update presence after session revocation:",
      presenceError,
    );
  }

  await writeAdminAuditLog({
    adminId:
      admin.id,

    actionType:
      "admin_sessions_revoked",

    description:
      "Administrator revoked all active administrator sessions.",

    targetTable:
      "admin_sessions",

    targetId:
      admin.id,
  });

  refreshAdminPages();

  return {
    success:
      true,

    message:
      "All administrator sessions have been signed out.",

    requiresReauth:
      true,
  };
}

/* =========================================================
   SAVE POLICY
========================================================= */

export async function savePolicySettingAction(
  input: {
    key:
      string;

    value:
      string;
  },
): Promise<PolicyActionResult> {
  const parsed =
    savePolicySchema.safeParse(
      input,
    );

  if (
    !parsed.success
  ) {
    return {
      success:
        false,

      message:
        parsed.error
          .issues[0]
          ?.message ??
        "Invalid policy value.",
    };
  }

  const admin =
    await requireAdmin();

  const supabase =
    getSupabaseAdmin();

  const {
    key,
    value,
  } =
    parsed.data;

  const {
    data:
      existingSetting,

    error:
      existingError,
  } =
    await supabase
      .from(
        "platform_settings",
      )
      .select(`
        id,
        key,
        value,
        type,
        grp,
        description,
        updated_by,
        updated_at
      `)
      .eq(
        "key",
        key,
      )
      .maybeSingle();

  if (
    existingError
  ) {
    console.error(
      "[ADMIN SETTINGS] Failed to verify policy:",
      existingError,
    );

    return {
      success:
        false,

      message:
        "Unable to verify this policy setting.",
    };
  }

  if (
    !existingSetting
  ) {
    return {
      success:
        false,

      message:
        "This policy does not exist.",
    };
  }

  /*
   * The Settings page may only update
   * rows that qualify as actual policy
   * or legal settings.
   *
   * Other generic platform_settings
   * records cannot be changed through
   * this action.
   */
  if (
    !isPolicySetting(
      existingSetting as RawPolicySetting,
    )
  ) {
    return {
      success:
        false,

      message:
        "This setting is not available in the Policies section.",
    };
  }

  if (
    (
      existingSetting.value ??
      ""
    ) ===
    value
  ) {
    return {
      success:
        true,

      message:
        "No policy changes were necessary.",

      setting: {
        id:
          Number(
            existingSetting.id,
          ),

        key:
          existingSetting.key,

        value:
          existingSetting.value,

        updated_by:
          existingSetting.updated_by,

        updated_at:
          existingSetting.updated_at,
      },
    };
  }

  const now =
    new Date()
      .toISOString();

  const {
    data:
      updatedSetting,

    error:
      updateError,
  } =
    await supabase
      .from(
        "platform_settings",
      )
      .update({
        value,

        updated_by:
          admin.id,

        updated_at:
          now,
      })
      .eq(
        "id",
        existingSetting.id,
      )
      .select(`
        id,
        key,
        value,
        updated_by,
        updated_at
      `)
      .single();

  if (
    updateError ||
    !updatedSetting
  ) {
    console.error(
      "[ADMIN SETTINGS] Failed to update policy:",
      updateError,
    );

    return {
      success:
        false,

      message:
        "Unable to save this policy.",
    };
  }

  await writeAdminAuditLog({
    adminId:
      admin.id,

    actionType:
      "platform_policy_updated",

    description:
      `Administrator updated policy "${updatedSetting.key}".`,

    targetTable:
      "platform_settings",

    targetId:
      String(
        updatedSetting.id,
      ),
  });

  refreshAdminPages();

  return {
    success:
      true,

    message:
      "Policy saved successfully.",

    setting: {
      id:
        Number(
          updatedSetting.id,
        ),

      key:
        updatedSetting.key,

      value:
        updatedSetting.value,

      updated_by:
        updatedSetting.updated_by,

      updated_at:
        updatedSetting.updated_at,
    },
  };
}